#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    localgov-microsites-d11-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^localgov-microsites-d11\.ddev\.site$`)
      
      service: "localgov-microsites-d11-web-80"
      tls: false
      # middlewares:
      #   - "localgov-microsites-d11-redirectHttps"
    localgov-microsites-d11-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^localgov-microsites-d11\.ddev\.site$`)
      
      service: "localgov-microsites-d11-web-8025"
      tls: false
      # middlewares:
      #   - "localgov-microsites-d11-redirectHttps"
    localgov-microsites-d11-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^localgov-microsites-d11\.ddev\.site$`)
      
      service: "localgov-microsites-d11-xhgui-80"
      tls: false
      # middlewares:
      #   - "localgov-microsites-d11-redirectHttps"
    
    
    
    localgov-microsites-d11-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^localgov-microsites-d11\.ddev\.site$`)
      
      service: "localgov-microsites-d11-web-80"
      
      tls: true
      
    localgov-microsites-d11-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^localgov-microsites-d11\.ddev\.site$`)
      
      service: "localgov-microsites-d11-web-8025"
      
      tls: true
      
    
    localgov-microsites-d11-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^localgov-microsites-d11\.ddev\.site$`)
      
      service: "localgov-microsites-d11-xhgui-80"
      
      tls: true
      
    

  middlewares:
    localgov-microsites-d11-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    localgov-microsites-d11-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-localgov-microsites-d11-web:80
        
    localgov-microsites-d11-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-localgov-microsites-d11-web:8025
        
    
    
    localgov-microsites-d11-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-localgov-microsites-d11-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/localgov-microsites-d11.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/localgov-microsites-d11.key